### ISSUE TITLE
dotcms.saml.policy.format not updated in generated sp metadata

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-dotcms-openSAML3#33]
dotcms.saml.policy.format=urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress should update the `<saml2p:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"/>` element in the generated sp metadata with the proper urn.

**Comment by jdotcms** [comment]
on it

**Comment by jdotcms** [comment]
in addtion we want to change the property to dotcms.saml.nameidpolicy.format
