### ISSUE TITLE
Allow SAML authentication to be enabled/disabled

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-dotcms-openSAML3#38]
This should be process:

- If samlEnabled is false and samlConfig is empty, we do nothing
- If samlEnabled is false and samlConfig is not empty, we validate samlConfig (but allow empty idp.metadata.path) and make sp metadata generated and available (without init’ing any other saml filter functionality)
- If samlEnabled is true and samlConfig is empty, we fail validation
- If samlEnabled is true and samlConfig is not empty, we fully-validate samlConfig (including idp.metadata.path) and make sp metadata generated and available, and we init the saml filter for that Site

`samlEnabled` is a host field (boolean, checkbox)
Current `saml` host field is changed to `samlConfig`. Label changed to "SAML Configuration" 
"samlConfig is empty" means there is nothing in the SAML config textarea at all

**Comment by jdotcms** [comment]
on it

**Comment by chrismccracken** [comment]
Passed QA on master
