### ISSUE TITLE
Simplify/fix config prop validation/defaults

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-dotcms-openSAML3#40]
UI should default to only 3 props (all mandatory, but see https://github.com/dotCMS/plugin-dotcms-openSAML3/issues/38 for `idp.metadata.path` specifics)

- `keystore.path`
- `keystore.password`
- `idp.metadata.path`

Additional common props (alter default values, make non-mandatory):
- `service.provider.issuer` (default to Site hostname with "https://" prefix, this might already be done)
- `keystore.entry.password` should default to value of `keystore.password` if not set
- `keyentryid` should default to “dotsamlsp” if not set (rename to `keystore.entry.id`)
- `remove.roles.prefix` and `include.roles.pattern` should default to empty

**Comment by jdotcms** [comment]
keystore.path
keystore.password
idp.metadata.path

Done

**Comment by jdotcms** [comment]
service.provider.issuer
This was already done

**Comment by jdotcms** [comment]
keystore.entry.password
DONE

**Comment by jdotcms** [comment]
keyentryid DONE

**Comment by jdotcms** [comment]
remove.roles.prefix
DONE

**Comment by chrismccracken** [comment]
Passed QA in master
