### ISSUE TITLE
Add option to force local auth and bypass SAML

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-dotcms-openSAML3#43]
Url query param on login page, must have local user account created beforehand with password set.

**Comment by jdotcms** [comment]
Tested locally on a three.dotcms.com server which is configure to samlEnable = true
![screen shot 2017-10-10 at 2 19 00 pm](https://user-images.githubusercontent.com/19578350/31408494-0403af14-adc6-11e7-8549-ac3d94f6c342.png)

Passing the native=true
![screen shot 2017-10-10 at 2 17 39 pm](https://user-images.githubusercontent.com/19578350/31408510-1603bf6a-adc6-11e7-8d95-7ee60c12a262.png)

You get the native dotCMS login
![screen shot 2017-10-10 at 2 17 46 pm](https://user-images.githubusercontent.com/19578350/31408523-23245eca-adc6-11e7-9b1c-0a80f3ee4fb9.png)

You can get log in:
Screen Shot 2017-10-10 at 2.20.32 PM

As soon as you get logout, saml bypass is over and you get back to the saml login:
![screen shot 2017-10-10 at 2 21 40 pm](https://user-images.githubusercontent.com/19578350/31408599-5c7b1204-adc6-11e7-88f2-1f8cc53bc4db.png)

**Comment by gabbydotCMS** [comment]
Works in release-4.2.x

**Comment by chrismccracken** [comment]
Verified in 3.7 branch
