### ISSUE TITLE
Better SAML filter init for cluster

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-dotcms-openSAML3#44]
- Create SAML configuration background thread started at init, lives forever.
- SAML config thread polls Site contentlets via contentapi.search() to get live, current Site contentlets, samlEnabled & samlConfig fields (field types must be indexed/searchable).
- SAML config thread calls saml code in try/catch Throwable to ensure it does not die on any error
- SAML config thread sleeps for a configurable time period (dotmarketing-config.props, default 10s)
- Remove current Publish Hook config process

**Comment by jdotcms** [comment]
On it

**Comment by jdotcms** [comment]
Note: when the live host list is retrieved, the list will be compare with the previous list stored, any site updated will be refresh the configuration and any missing host in the previous list will be removed (since it means the host were deleted/archive or unpublish)

**Comment by chrismccracken** [comment]
Passed QA on master
