### ISSUE TITLE
Staged validation

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-dotcms-openSAML3#48]
Allow 2-stage config process to be able to generate sp metadata prior to SAML filter activation.

On Site publish hook:

if samlEnabled == false && ( isSet(samlConfig.keystore.path) && isSet(samlConfig.keystore.password) ) then we do a soft validation of the params needed to generate the sp metadata:

- keystore.path
- keystore.password
- keystore.entry.password (default to value of keystore.password if not set)
- keystore.entry.id (default to dotsamlsp)
- service.provider.issuer (default to Site hostname with "https://" prefix
- assertion.customer.endpoint.url (default to service.provider.issuer/dotsaml3sp)
- logout.service.endpoint.url (default to service.provider.issuer/dotsaml3sp-logout)
- nameidpolicy.format (default unchanged)
- want.assertions.signed (default true)
- authn.requests.signed (default true)

if samlEnabled == true, then we do full validation of all props

**Comment by jdotcms** [comment]
Just to clarify, we changed 
assertion.customer.endpoint.url 
from this "dotsaml3sp" to this "/dotsaml/login”

logout.service.endpoint.url 
from this  “/dotsaml/logout” to this “/dotsaml3sp-logout”

Also the default for nameidpolicy.format is PERSISTANCE

**Comment by jdotcms** [comment]
It seems the configuration defaults were set ok in a previous ticket, we just double check.
Going to work on the metadata generation when the saml is disable

**Comment by gabbydotCMS** [comment]
This works as expected on release-4.2.x

**Comment by chrismccracken** [comment]
Passed QA on 3.7 branch
